// Code generated by ent, DO NOT EDIT.

package seat

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the seat type in the database.
	Label = "seat"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFlightID holds the string denoting the flight_id field in the database.
	FieldFlightID = "flight_id"
	// FieldSeatNumber holds the string denoting the seat_number field in the database.
	FieldSeatNumber = "seat_number"
	// Table holds the table name of the seat in the database.
	Table = "seats"
)

// Columns holds all SQL columns for seat fields.
var Columns = []string{
	FieldID,
	FieldFlightID,
	FieldSeatNumber,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "seats"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"flight_seats",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Seat queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByFlightID orders the results by the flight_id field.
func ByFlightID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFlightID, opts...).ToFunc()
}

// BySeatNumber orders the results by the seat_number field.
func BySeatNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeatNumber, opts...).ToFunc()
}
