package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"flookybooky/pb"
	"flookybooky/services/graphql/gql_generated"
	"flookybooky/services/graphql/internal"
	"flookybooky/services/graphql/model"

	"google.golang.org/protobuf/types/known/emptypb"
)

// GoingFlight is the resolver for the going_flight field.
func (r *bookingResolver) GoingFlight(ctx context.Context, obj *model.Booking) (*model.Flight, error) {
	var out *model.Flight
	if obj.GoingFlight != nil {
		flightRes, err := r.client.FlightClient.GetFlight(ctx, &pb.UUID{Id: obj.GoingFlight.ID})
		if err != nil {
			return nil, err
		}
		out = internal.ParseFlightPbToGraphql(flightRes)
	}
	return out, nil
}

// ReturnFlight is the resolver for the return_flight field.
func (r *bookingResolver) ReturnFlight(ctx context.Context, obj *model.Booking) (*model.Flight, error) {
	var out *model.Flight
	if obj.ReturnFlight != nil {
		flightRes, err := r.client.FlightClient.GetFlight(ctx, &pb.UUID{Id: obj.ReturnFlight.ID})
		if err != nil {
			return nil, err
		}
		out = internal.ParseFlightPbToGraphql(flightRes)
	}
	return out, nil
}

// Customer is the resolver for the customer field.
func (r *bookingResolver) Customer(ctx context.Context, obj *model.Booking) (*model.Customer, error) {
	var out *model.Customer
	if obj.Customer != nil {
		customerRes, err := r.client.CustomerClient.GetCustomer(ctx, &pb.UUID{Id: obj.Customer.ID})
		if err != nil {
			return nil, err
		}
		out = internal.ParseCustomerPbToGraphql(customerRes)
	}
	return out, nil
}

// CreateBooking is the resolver for the createBooking field.
func (r *mutationResolver) CreateBooking(ctx context.Context, input model.BookingInput) (*model.Booking, error) {
	_, err := r.client.CustomerClient.GetCustomer(ctx, &pb.UUID{
		Id: input.CustomerID,
	})
	if err != nil {
		return nil, err
	}
	_, err = r.client.FlightClient.GetFlight(ctx, &pb.UUID{
		Id: input.GoingFlightID,
	})
	if err != nil {
		return nil, err
	}
	if input.ReturnFlightID != nil {
		_, err = r.client.FlightClient.GetFlight(ctx, &pb.UUID{
			Id: *input.ReturnFlightID,
		})
		if err != nil {
			return nil, err
		}
	}
	bookingRes, err := r.client.BookingClient.PostBooking(ctx, internal.ParseBookingInputGraphqlToPb(&input))
	return internal.ParseBookingPbToGraphql(bookingRes), err
}

// Booking is the resolver for the booking field.
func (r *queryResolver) Booking(ctx context.Context) ([]*model.Booking, error) {
	bookingsRes, err := r.client.BookingClient.GetBookings(ctx, &emptypb.Empty{})
	return internal.ParseBookingsPbToGraphql(bookingsRes), err
}

// Booking returns gql_generated.BookingResolver implementation.
func (r *Resolver) Booking() gql_generated.BookingResolver { return &bookingResolver{r} }

type bookingResolver struct{ *Resolver }
