package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"flookybooky/services/graphql/internal"
	"flookybooky/services/graphql/model"

	"google.golang.org/protobuf/types/known/emptypb"
)

// CreateCustomer is the resolver for the createCustomer field.
func (r *mutationResolver) CreateCustomer(ctx context.Context, input model.CustomerInput) (*model.Customer, error) {
	customerRes, err := r.client.CustomerClient.PostCustomer(ctx,
		internal.ParseCustomerInputGraphqlToPb(&input),
	)
	if err != nil {
		return nil, err
	}
	return internal.ParseCustomerPbToGraphql(customerRes), nil
}

// Customers is the resolver for the customers field.
func (r *queryResolver) Customers(ctx context.Context, id *string, name *string) ([]*model.Customer, error) {
	customersRes, err := r.client.CustomerClient.GetCustomers(ctx, &emptypb.Empty{})
	if err != nil {
		return nil, err
	}
	return internal.ParseCustomersPbToGraphql(customersRes), nil
}
