package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"flookybooky/pb"
	"flookybooky/services/graphql/gql_generated"
	"flookybooky/services/graphql/internal"
	"flookybooky/services/graphql/model"
)

// Ticket is the resolver for the ticket field.
func (r *queryResolver) Ticket(ctx context.Context, input *model.Pagination) ([]*model.Ticket, error) {
	ticketsRes, err := r.client.BookingClient.GetTickets(ctx,
		internal.ParsePaginationGraphqlToPb(input))
	return internal.ParseTicketsPbToGraphqlTo(ticketsRes), err
}

// Flight is the resolver for the flight field.
func (r *ticketResolver) Flight(ctx context.Context, obj *model.Ticket) (*model.Flight, error) {
	if obj.Flight == nil {
		return nil, nil
	}
	flightRes, err := r.client.FlightClient.GetFlight(ctx, &pb.UUID{Id: obj.Flight.ID})
	return internal.ParseFlightPbToGraphql(flightRes), err
}

// Ticket returns gql_generated.TicketResolver implementation.
func (r *Resolver) Ticket() gql_generated.TicketResolver { return &ticketResolver{r} }

type ticketResolver struct{ *Resolver }
