package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"flookybooky/internal/util"
	"flookybooky/pb"
	"flookybooky/services/graphql/gql_generated"
	"flookybooky/services/graphql/internal"
	"flookybooky/services/graphql/model"

	"github.com/gin-gonic/gin"
	"github.com/jinzhu/copier"
	"google.golang.org/protobuf/types/known/emptypb"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.UserInput) (*model.User, error) {
	userReq := internal.ParseUserInputGraphqlToPb(&input)
	if input.Customer != nil {
		customerRes, err := r.client.CustomerClient.PostCustomer(ctx,
			internal.ParseCustomerInputGraphqlToPb(input.Customer))
		if err != nil {
			return nil, err
		}
		userReq.Customer = customerRes
	}
	userRes, err := r.client.UserClient.PostUser(ctx, userReq)
	if err != nil {
		return nil, err
	}
	return internal.ParseUserPbToGraphql(userRes), nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.LoginInfo, error) {
	res, err := r.client.UserClient.Login(ctx,
		&pb.LoginRequest{
			User: &pb.User{
				Username: input.Username,
				Password: input.Password,
			},
		},
	)

	if err != nil {
		return nil, err
	}

	c, _ := ctx.Value(util.ContextKey{}).(*gin.Context)
	c.SetCookie(
		"Authentication", res.JwtToken,
		int(res.ExpireTime), "", "", false, false,
	)
	return &model.LoginInfo{
		TokenString: res.JwtToken,
	}, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	usersRes, err := r.client.UserClient.GetUsers(ctx, &emptypb.Empty{})
	return internal.ParseUsersPbToGraphql(usersRes), err
}

// Customer is the resolver for the customer field.
func (r *userResolver) Customer(ctx context.Context, obj *model.User) (*model.Customer, error) {
	var out *model.Customer
	if obj.Customer != nil {
		out = &model.Customer{}
		req := &pb.GetCustomerRequest{
			Id: obj.Customer.ID,
		}
		customerRes, err := r.client.CustomerClient.GetCustomer(ctx, req)
		if err != nil {
			return nil, err
		}

		copier.Copy(&out, customerRes)
		out.ID = customerRes.Id
		out.LicenseID = customerRes.LicenseId
	}
	return out, nil
}

// User returns gql_generated.UserResolver implementation.
func (r *Resolver) User() gql_generated.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
