services:

  adminer:
    profiles: ["all"]
    image: adminer
    restart: always
    ports:
      - 9999:8080

  petdb:
    profiles: ["pet", "all"]
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: pet
      POSTGRES_USER: root
      POSTGRES_PASSWORD: passwd
    ports:
      - 54320:5432
  
  pet:
    profiles: ["pet", "all"]
    build:
      context: .
      dockerfile: ./pet/pet.dockerfile
    restart: on-failure
    ports:
      - 2220:2220

  userdb:
    profiles: ["user", "all"]
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: root
      POSTGRES_PASSWORD: passwd
    ports:
      - 54321:5432
  
  user:
    profiles: ["user", "all"]
    build:
      context: .
      dockerfile: ./user/user.dockerfile
    restart: on-failure
    ports:
      - 2221:2220
  
  graphql:
    profiles: ["all"]
    build:
      context: .
      dockerfile: ./graphql/graphql.dockerfile
    restart: on-failure
    ports:
      - 8081:8081