// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Airport is the predicate function for airport builders.
type Airport func(*sql.Selector)

// Flight is the predicate function for flight builders.
type Flight func(*sql.Selector)

// Seat is the predicate function for seat builders.
type Seat func(*sql.Selector)
