// Code generated by ent, DO NOT EDIT.

package ent

import (
	"flookybooky/flight/ent/flight"
	"flookybooky/flight/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	flightFields := schema.Flight{}.Fields()
	_ = flightFields
	// flightDescCreatedAt is the schema descriptor for created_at field.
	flightDescCreatedAt := flightFields[6].Descriptor()
	// flight.DefaultCreatedAt holds the default value on creation for the created_at field.
	flight.DefaultCreatedAt = flightDescCreatedAt.Default.(func() time.Time)
}
