// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BookingsColumns holds the columns for the "bookings" table.
	BookingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "customer_id", Type: field.TypeUUID},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"Canceled", "Scheduled", "Departed"}},
		{Name: "created_at", Type: field.TypeTime},
	}
	// BookingsTable holds the schema information for the "bookings" table.
	BookingsTable = &schema.Table{
		Name:       "bookings",
		Columns:    BookingsColumns,
		PrimaryKey: []*schema.Column{BookingsColumns[0]},
	}
	// TicketsColumns holds the columns for the "tickets" table.
	TicketsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "going_flight_id", Type: field.TypeUUID},
		{Name: "return_flight_id", Type: field.TypeUUID, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"Canceled", "Departed", "Scheduled"}},
		{Name: "passenger_name", Type: field.TypeString},
		{Name: "passenger_license_id", Type: field.TypeString},
		{Name: "passenger_email", Type: field.TypeString},
		{Name: "seat_number", Type: field.TypeString},
		{Name: "class", Type: field.TypeEnum, Enums: []string{"FirstClass", "BusinessClass", "EconomyClass"}},
		{Name: "booking_id", Type: field.TypeUUID},
	}
	// TicketsTable holds the schema information for the "tickets" table.
	TicketsTable = &schema.Table{
		Name:       "tickets",
		Columns:    TicketsColumns,
		PrimaryKey: []*schema.Column{TicketsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tickets_bookings_ticket",
				Columns:    []*schema.Column{TicketsColumns[9]},
				RefColumns: []*schema.Column{BookingsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BookingsTable,
		TicketsTable,
	}
)

func init() {
	TicketsTable.ForeignKeys[0].RefTable = BookingsTable
}
