// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"flookybooky/services/flight/ent/airport"
	"flookybooky/services/flight/ent/flight"
	"flookybooky/services/flight/ent/predicate"
	"flookybooky/services/flight/ent/seat"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// FlightUpdate is the builder for updating Flight entities.
type FlightUpdate struct {
	config
	hooks    []Hook
	mutation *FlightMutation
}

// Where appends a list predicates to the FlightUpdate builder.
func (fu *FlightUpdate) Where(ps ...predicate.Flight) *FlightUpdate {
	fu.mutation.Where(ps...)
	return fu
}

// SetName sets the "name" field.
func (fu *FlightUpdate) SetName(s string) *FlightUpdate {
	fu.mutation.SetName(s)
	return fu
}

// SetOriginID sets the "origin_id" field.
func (fu *FlightUpdate) SetOriginID(u uuid.UUID) *FlightUpdate {
	fu.mutation.SetOriginID(u)
	return fu
}

// SetDestinartionID sets the "destinartion_id" field.
func (fu *FlightUpdate) SetDestinartionID(u uuid.UUID) *FlightUpdate {
	fu.mutation.SetDestinartionID(u)
	return fu
}

// SetDepartureTime sets the "departure_time" field.
func (fu *FlightUpdate) SetDepartureTime(t time.Time) *FlightUpdate {
	fu.mutation.SetDepartureTime(t)
	return fu
}

// SetArrivalTime sets the "arrival_time" field.
func (fu *FlightUpdate) SetArrivalTime(t time.Time) *FlightUpdate {
	fu.mutation.SetArrivalTime(t)
	return fu
}

// SetAvailableSlots sets the "available_slots" field.
func (fu *FlightUpdate) SetAvailableSlots(i int) *FlightUpdate {
	fu.mutation.ResetAvailableSlots()
	fu.mutation.SetAvailableSlots(i)
	return fu
}

// AddAvailableSlots adds i to the "available_slots" field.
func (fu *FlightUpdate) AddAvailableSlots(i int) *FlightUpdate {
	fu.mutation.AddAvailableSlots(i)
	return fu
}

// SetStatus sets the "status" field.
func (fu *FlightUpdate) SetStatus(f flight.Status) *FlightUpdate {
	fu.mutation.SetStatus(f)
	return fu
}

// AddSeatIDs adds the "seats" edge to the Seat entity by IDs.
func (fu *FlightUpdate) AddSeatIDs(ids ...uuid.UUID) *FlightUpdate {
	fu.mutation.AddSeatIDs(ids...)
	return fu
}

// AddSeats adds the "seats" edges to the Seat entity.
func (fu *FlightUpdate) AddSeats(s ...*Seat) *FlightUpdate {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return fu.AddSeatIDs(ids...)
}

// SetOrigin sets the "origin" edge to the Airport entity.
func (fu *FlightUpdate) SetOrigin(a *Airport) *FlightUpdate {
	return fu.SetOriginID(a.ID)
}

// SetDestinationID sets the "destination" edge to the Airport entity by ID.
func (fu *FlightUpdate) SetDestinationID(id uuid.UUID) *FlightUpdate {
	fu.mutation.SetDestinationID(id)
	return fu
}

// SetDestination sets the "destination" edge to the Airport entity.
func (fu *FlightUpdate) SetDestination(a *Airport) *FlightUpdate {
	return fu.SetDestinationID(a.ID)
}

// Mutation returns the FlightMutation object of the builder.
func (fu *FlightUpdate) Mutation() *FlightMutation {
	return fu.mutation
}

// ClearSeats clears all "seats" edges to the Seat entity.
func (fu *FlightUpdate) ClearSeats() *FlightUpdate {
	fu.mutation.ClearSeats()
	return fu
}

// RemoveSeatIDs removes the "seats" edge to Seat entities by IDs.
func (fu *FlightUpdate) RemoveSeatIDs(ids ...uuid.UUID) *FlightUpdate {
	fu.mutation.RemoveSeatIDs(ids...)
	return fu
}

// RemoveSeats removes "seats" edges to Seat entities.
func (fu *FlightUpdate) RemoveSeats(s ...*Seat) *FlightUpdate {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return fu.RemoveSeatIDs(ids...)
}

// ClearOrigin clears the "origin" edge to the Airport entity.
func (fu *FlightUpdate) ClearOrigin() *FlightUpdate {
	fu.mutation.ClearOrigin()
	return fu
}

// ClearDestination clears the "destination" edge to the Airport entity.
func (fu *FlightUpdate) ClearDestination() *FlightUpdate {
	fu.mutation.ClearDestination()
	return fu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (fu *FlightUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, FlightMutation](ctx, fu.sqlSave, fu.mutation, fu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fu *FlightUpdate) SaveX(ctx context.Context) int {
	affected, err := fu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (fu *FlightUpdate) Exec(ctx context.Context) error {
	_, err := fu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fu *FlightUpdate) ExecX(ctx context.Context) {
	if err := fu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fu *FlightUpdate) check() error {
	if v, ok := fu.mutation.Status(); ok {
		if err := flight.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Flight.status": %w`, err)}
		}
	}
	if _, ok := fu.mutation.OriginID(); fu.mutation.OriginCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Flight.origin"`)
	}
	if _, ok := fu.mutation.DestinationID(); fu.mutation.DestinationCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Flight.destination"`)
	}
	return nil
}

func (fu *FlightUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := fu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(flight.Table, flight.Columns, sqlgraph.NewFieldSpec(flight.FieldID, field.TypeUUID))
	if ps := fu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fu.mutation.Name(); ok {
		_spec.SetField(flight.FieldName, field.TypeString, value)
	}
	if value, ok := fu.mutation.DepartureTime(); ok {
		_spec.SetField(flight.FieldDepartureTime, field.TypeTime, value)
	}
	if value, ok := fu.mutation.ArrivalTime(); ok {
		_spec.SetField(flight.FieldArrivalTime, field.TypeTime, value)
	}
	if value, ok := fu.mutation.AvailableSlots(); ok {
		_spec.SetField(flight.FieldAvailableSlots, field.TypeInt, value)
	}
	if value, ok := fu.mutation.AddedAvailableSlots(); ok {
		_spec.AddField(flight.FieldAvailableSlots, field.TypeInt, value)
	}
	if value, ok := fu.mutation.Status(); ok {
		_spec.SetField(flight.FieldStatus, field.TypeEnum, value)
	}
	if fu.mutation.SeatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.SeatsTable,
			Columns: []string{flight.SeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seat.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fu.mutation.RemovedSeatsIDs(); len(nodes) > 0 && !fu.mutation.SeatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.SeatsTable,
			Columns: []string{flight.SeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fu.mutation.SeatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.SeatsTable,
			Columns: []string{flight.SeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if fu.mutation.OriginCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.OriginTable,
			Columns: []string{flight.OriginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(airport.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fu.mutation.OriginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.OriginTable,
			Columns: []string{flight.OriginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(airport.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if fu.mutation.DestinationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.DestinationTable,
			Columns: []string{flight.DestinationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(airport.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fu.mutation.DestinationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.DestinationTable,
			Columns: []string{flight.DestinationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(airport.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, fu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{flight.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	fu.mutation.done = true
	return n, nil
}

// FlightUpdateOne is the builder for updating a single Flight entity.
type FlightUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FlightMutation
}

// SetName sets the "name" field.
func (fuo *FlightUpdateOne) SetName(s string) *FlightUpdateOne {
	fuo.mutation.SetName(s)
	return fuo
}

// SetOriginID sets the "origin_id" field.
func (fuo *FlightUpdateOne) SetOriginID(u uuid.UUID) *FlightUpdateOne {
	fuo.mutation.SetOriginID(u)
	return fuo
}

// SetDestinartionID sets the "destinartion_id" field.
func (fuo *FlightUpdateOne) SetDestinartionID(u uuid.UUID) *FlightUpdateOne {
	fuo.mutation.SetDestinartionID(u)
	return fuo
}

// SetDepartureTime sets the "departure_time" field.
func (fuo *FlightUpdateOne) SetDepartureTime(t time.Time) *FlightUpdateOne {
	fuo.mutation.SetDepartureTime(t)
	return fuo
}

// SetArrivalTime sets the "arrival_time" field.
func (fuo *FlightUpdateOne) SetArrivalTime(t time.Time) *FlightUpdateOne {
	fuo.mutation.SetArrivalTime(t)
	return fuo
}

// SetAvailableSlots sets the "available_slots" field.
func (fuo *FlightUpdateOne) SetAvailableSlots(i int) *FlightUpdateOne {
	fuo.mutation.ResetAvailableSlots()
	fuo.mutation.SetAvailableSlots(i)
	return fuo
}

// AddAvailableSlots adds i to the "available_slots" field.
func (fuo *FlightUpdateOne) AddAvailableSlots(i int) *FlightUpdateOne {
	fuo.mutation.AddAvailableSlots(i)
	return fuo
}

// SetStatus sets the "status" field.
func (fuo *FlightUpdateOne) SetStatus(f flight.Status) *FlightUpdateOne {
	fuo.mutation.SetStatus(f)
	return fuo
}

// AddSeatIDs adds the "seats" edge to the Seat entity by IDs.
func (fuo *FlightUpdateOne) AddSeatIDs(ids ...uuid.UUID) *FlightUpdateOne {
	fuo.mutation.AddSeatIDs(ids...)
	return fuo
}

// AddSeats adds the "seats" edges to the Seat entity.
func (fuo *FlightUpdateOne) AddSeats(s ...*Seat) *FlightUpdateOne {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return fuo.AddSeatIDs(ids...)
}

// SetOrigin sets the "origin" edge to the Airport entity.
func (fuo *FlightUpdateOne) SetOrigin(a *Airport) *FlightUpdateOne {
	return fuo.SetOriginID(a.ID)
}

// SetDestinationID sets the "destination" edge to the Airport entity by ID.
func (fuo *FlightUpdateOne) SetDestinationID(id uuid.UUID) *FlightUpdateOne {
	fuo.mutation.SetDestinationID(id)
	return fuo
}

// SetDestination sets the "destination" edge to the Airport entity.
func (fuo *FlightUpdateOne) SetDestination(a *Airport) *FlightUpdateOne {
	return fuo.SetDestinationID(a.ID)
}

// Mutation returns the FlightMutation object of the builder.
func (fuo *FlightUpdateOne) Mutation() *FlightMutation {
	return fuo.mutation
}

// ClearSeats clears all "seats" edges to the Seat entity.
func (fuo *FlightUpdateOne) ClearSeats() *FlightUpdateOne {
	fuo.mutation.ClearSeats()
	return fuo
}

// RemoveSeatIDs removes the "seats" edge to Seat entities by IDs.
func (fuo *FlightUpdateOne) RemoveSeatIDs(ids ...uuid.UUID) *FlightUpdateOne {
	fuo.mutation.RemoveSeatIDs(ids...)
	return fuo
}

// RemoveSeats removes "seats" edges to Seat entities.
func (fuo *FlightUpdateOne) RemoveSeats(s ...*Seat) *FlightUpdateOne {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return fuo.RemoveSeatIDs(ids...)
}

// ClearOrigin clears the "origin" edge to the Airport entity.
func (fuo *FlightUpdateOne) ClearOrigin() *FlightUpdateOne {
	fuo.mutation.ClearOrigin()
	return fuo
}

// ClearDestination clears the "destination" edge to the Airport entity.
func (fuo *FlightUpdateOne) ClearDestination() *FlightUpdateOne {
	fuo.mutation.ClearDestination()
	return fuo
}

// Where appends a list predicates to the FlightUpdate builder.
func (fuo *FlightUpdateOne) Where(ps ...predicate.Flight) *FlightUpdateOne {
	fuo.mutation.Where(ps...)
	return fuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (fuo *FlightUpdateOne) Select(field string, fields ...string) *FlightUpdateOne {
	fuo.fields = append([]string{field}, fields...)
	return fuo
}

// Save executes the query and returns the updated Flight entity.
func (fuo *FlightUpdateOne) Save(ctx context.Context) (*Flight, error) {
	return withHooks[*Flight, FlightMutation](ctx, fuo.sqlSave, fuo.mutation, fuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fuo *FlightUpdateOne) SaveX(ctx context.Context) *Flight {
	node, err := fuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (fuo *FlightUpdateOne) Exec(ctx context.Context) error {
	_, err := fuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fuo *FlightUpdateOne) ExecX(ctx context.Context) {
	if err := fuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fuo *FlightUpdateOne) check() error {
	if v, ok := fuo.mutation.Status(); ok {
		if err := flight.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Flight.status": %w`, err)}
		}
	}
	if _, ok := fuo.mutation.OriginID(); fuo.mutation.OriginCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Flight.origin"`)
	}
	if _, ok := fuo.mutation.DestinationID(); fuo.mutation.DestinationCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Flight.destination"`)
	}
	return nil
}

func (fuo *FlightUpdateOne) sqlSave(ctx context.Context) (_node *Flight, err error) {
	if err := fuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(flight.Table, flight.Columns, sqlgraph.NewFieldSpec(flight.FieldID, field.TypeUUID))
	id, ok := fuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Flight.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := fuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, flight.FieldID)
		for _, f := range fields {
			if !flight.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != flight.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := fuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fuo.mutation.Name(); ok {
		_spec.SetField(flight.FieldName, field.TypeString, value)
	}
	if value, ok := fuo.mutation.DepartureTime(); ok {
		_spec.SetField(flight.FieldDepartureTime, field.TypeTime, value)
	}
	if value, ok := fuo.mutation.ArrivalTime(); ok {
		_spec.SetField(flight.FieldArrivalTime, field.TypeTime, value)
	}
	if value, ok := fuo.mutation.AvailableSlots(); ok {
		_spec.SetField(flight.FieldAvailableSlots, field.TypeInt, value)
	}
	if value, ok := fuo.mutation.AddedAvailableSlots(); ok {
		_spec.AddField(flight.FieldAvailableSlots, field.TypeInt, value)
	}
	if value, ok := fuo.mutation.Status(); ok {
		_spec.SetField(flight.FieldStatus, field.TypeEnum, value)
	}
	if fuo.mutation.SeatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.SeatsTable,
			Columns: []string{flight.SeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seat.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fuo.mutation.RemovedSeatsIDs(); len(nodes) > 0 && !fuo.mutation.SeatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.SeatsTable,
			Columns: []string{flight.SeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fuo.mutation.SeatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.SeatsTable,
			Columns: []string{flight.SeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if fuo.mutation.OriginCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.OriginTable,
			Columns: []string{flight.OriginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(airport.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fuo.mutation.OriginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.OriginTable,
			Columns: []string{flight.OriginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(airport.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if fuo.mutation.DestinationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.DestinationTable,
			Columns: []string{flight.DestinationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(airport.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fuo.mutation.DestinationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.DestinationTable,
			Columns: []string{flight.DestinationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(airport.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Flight{config: fuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, fuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{flight.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	fuo.mutation.done = true
	return _node, nil
}
