// Code generated by ent, DO NOT EDIT.

package flight

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the flight type in the database.
	Label = "flight"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldOriginID holds the string denoting the origin_id field in the database.
	FieldOriginID = "origin_id"
	// FieldDestinartionID holds the string denoting the destinartion_id field in the database.
	FieldDestinartionID = "destinartion_id"
	// FieldDepartureTime holds the string denoting the departure_time field in the database.
	FieldDepartureTime = "departure_time"
	// FieldArrivalTime holds the string denoting the arrival_time field in the database.
	FieldArrivalTime = "arrival_time"
	// FieldAvailableSlots holds the string denoting the available_slots field in the database.
	FieldAvailableSlots = "available_slots"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeSeats holds the string denoting the seats edge name in mutations.
	EdgeSeats = "seats"
	// EdgeOrigin holds the string denoting the origin edge name in mutations.
	EdgeOrigin = "origin"
	// EdgeDestination holds the string denoting the destination edge name in mutations.
	EdgeDestination = "destination"
	// Table holds the table name of the flight in the database.
	Table = "flights"
	// SeatsTable is the table that holds the seats relation/edge.
	SeatsTable = "seats"
	// SeatsInverseTable is the table name for the Seat entity.
	// It exists in this package in order to avoid circular dependency with the "seat" package.
	SeatsInverseTable = "seats"
	// SeatsColumn is the table column denoting the seats relation/edge.
	SeatsColumn = "flight_seats"
	// OriginTable is the table that holds the origin relation/edge.
	OriginTable = "flights"
	// OriginInverseTable is the table name for the Airport entity.
	// It exists in this package in order to avoid circular dependency with the "airport" package.
	OriginInverseTable = "airports"
	// OriginColumn is the table column denoting the origin relation/edge.
	OriginColumn = "origin_id"
	// DestinationTable is the table that holds the destination relation/edge.
	DestinationTable = "flights"
	// DestinationInverseTable is the table name for the Airport entity.
	// It exists in this package in order to avoid circular dependency with the "airport" package.
	DestinationInverseTable = "airports"
	// DestinationColumn is the table column denoting the destination relation/edge.
	DestinationColumn = "destinartion_id"
)

// Columns holds all SQL columns for flight fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldOriginID,
	FieldDestinartionID,
	FieldDepartureTime,
	FieldArrivalTime,
	FieldAvailableSlots,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Flight queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByOriginID orders the results by the origin_id field.
func ByOriginID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginID, opts...).ToFunc()
}

// ByDestinartionID orders the results by the destinartion_id field.
func ByDestinartionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDestinartionID, opts...).ToFunc()
}

// ByDepartureTime orders the results by the departure_time field.
func ByDepartureTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDepartureTime, opts...).ToFunc()
}

// ByArrivalTime orders the results by the arrival_time field.
func ByArrivalTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArrivalTime, opts...).ToFunc()
}

// ByAvailableSlots orders the results by the available_slots field.
func ByAvailableSlots(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvailableSlots, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// BySeatsCount orders the results by seats count.
func BySeatsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSeatsStep(), opts...)
	}
}

// BySeats orders the results by seats terms.
func BySeats(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSeatsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByOriginField orders the results by origin field.
func ByOriginField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOriginStep(), sql.OrderByField(field, opts...))
	}
}

// ByDestinationField orders the results by destination field.
func ByDestinationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDestinationStep(), sql.OrderByField(field, opts...))
	}
}
func newSeatsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SeatsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SeatsTable, SeatsColumn),
	)
}
func newOriginStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OriginInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OriginTable, OriginColumn),
	)
}
func newDestinationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DestinationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DestinationTable, DestinationColumn),
	)
}
